package com.arthurprojects.pezesha.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity class representing an Account in the database.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "accounts")
public class Account {

    /**
     * Primary key of the Account entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the account holder.
     * Cannot be null and maps to the 'account_name' column.
     */
    @Column(name = "account_name", nullable = false)
    private String accountName;

    /**
     * Current balance of the account.
     * Cannot be null.
     */
    @Column(nullable = false)
    private BigDecimal balance;

    /**
     * Timestamp indicating when the account was created.
     * Automatically set before persistence.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp indicating when the account was last updated.
     * Automatically set before each update.
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Version field for optimistic locking.
     */
    @Version
    private Long version;

    /**
     * Automatically sets the creation and update timestamps
     * before the entity is persisted to the database.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        createdAt = now;
        updatedAt = now;
    }

    /**
     * Automatically updates the timestamp
     * before the entity is updated in the database.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
